### ISSUE TITLE
Invalid e-mail addresses being generated

### ISSUE THREAD

**Issue by johnknoop** [aliostad/RandomGen#10]
Hi

I get domain names with arabic or hindu characters or something.

I use these email addresses to create fake users with a third party system, which appaently checks email addresses for vailidity.

Could you add some sanity checking to e-mails? I'm not talking about checking that domain names exist or anything like that, but at least generate valid characters.

**Comment by jkonecki** [comment]
I believe the addresses are valid. It may be the case if the third party that doesn't support internationalised domain names.

https://en.m.wikipedia.org/wiki/Internationalized_domain_name

@aliostad do you want to support ASCII-only names?
