### ISSUE TITLE
Remove offensive name

### ISSUE THREAD

**Issue by CaryJ** [aliostad/RandomGen#12]
We use this library to generate random names in the demo environment of our product.  A customer was recently offended by the name "Rivka Shyrock", because of Rivka being a Jewish first name, and Shyrock being very close to Shylock, which is a character in Shakespeare that is offensive to Jews.
I suggest replacing "Shyrock" with some other last name.
I understand it's hard to foresee possible combinations of names that could be considered offensive in various cultures.  We have worked around this in our code, but want to make you aware of the potential issue.

**Comment by aliostad** [comment]
Hi, the least we would want to do is to offend anyone. And change is simple, yet for the reasons I will explain, it is not the right thing as a matter of principle.

The data is the exact copy of names collected from 1990 US census:
[https://www.census.gov/topics/population/genealogy/data/1990_census/1990_census_namefiles.html](1990 US Census)

![image](https://user-images.githubusercontent.com/487334/63845254-a2c08180-c981-11e9-96b4-4c72c6b0b082.png)


These are real names of the real people - offensive or not they are real. We also have the names Adolfo and even Adolph which I am sure offensive to many. So all in all, name of the people should not be offensive, let alone similarity.

Is this an acceptable explanation which these names are real names? If not, we can come of up some alternatives.
