### ISSUE TITLE
Adding support for System.Numerics.BigInteger

### ISSUE THREAD

**Issue by Reapism** [aliostad/RandomGen#15]
The `System.Numerics.BigInteger` class is used to generate arbitrarily large integers.

Extending the text generator to just generate numbers but return a string would add this quite easily. Using `BigInteger.Parse(string)`

**Comment by aliostad** [comment]
Do you need this feature?
It is kind of a hack really - ideally generating this should require cryptography.

If you have a use for this feature I guess we could accept a PR for it.
