### ISSUE TITLE
Every number generator throws exception for equal arguments

### ISSUE THREAD

**Issue by trandus** [aliostad/RandomGen#16]
Each of the following examples throws the exception:
_Specified argument was out of the range of valid values.
Parameter name: min >= max_

var _int = RandomGen.Gen.Random.Numbers.Integers(1, 1)();
var _decimal = RandomGen.Gen.Random.Numbers.Decimals(1, 1)();
var _double = RandomGen.Gen.Random.Numbers.Doubles(1, 1)();
var _long = RandomGen.Gen.Random.Numbers.Longs(1, 1)();
var _uint = RandomGen.Gen.Random.Numbers.UnsignedIntegers(1, 1)();

**Comment by jkonecki** [comment]
Thanks, Michal! I'll work on the fix soon and will let you know when a new NuGet is released

**Comment by jkonecki** [comment]
Actually this is a desired behaviour. There's no point in generating a random number between 1 and 1 as it will always be 1 ;-)

**Comment by trandus** [comment]
> a random number between 1 and 1 as it will always be 1 ;-)

Of course :)
Sometimes it is needed, for instance it helps get random item from array of non-zero and unknown length: array[Gen.Random.Numbers.Integers(0, array.Count-1)()]

**Comment by jkonecki** [comment]
For getting a random item from an array you migth want to use `Random.Gen.Items(array)`

**Comment by trandus** [comment]
Yeah, that's easy :) Thanks.
