### ISSUE TITLE
Every number generator throws exception for equal arguments

### ISSUE THREAD

**Issue by trandus** [aliostad/RandomGen#17]
Each of the following examples throws the exception:
_Specified argument was out of the range of valid values.
Parameter name: min >= max_

`var @int = RandomGen.Gen.Random.Numbers.Integers(1, 1)();
var @decimal = RandomGen.Gen.Random.Numbers.Decimals(1, 1)();
var @double = RandomGen.Gen.Random.Numbers.Doubles(1, 1)();
var @long = RandomGen.Gen.Random.Numbers.Longs(1, 1)();
var @uint = RandomGen.Gen.Random.Numbers.UnsignedIntegers(1, 1)();`

**Comment by jkonecki** [comment]
Duplicate of #16
