### ISSUE TITLE
Extending Adding my own

### ISSUE THREAD

**Issue by patagoniahiker** [aliostad/RandomGen#9]
Hi great framework :+1: how can I extend this to other values,

There is a lack of tools like this. 

It would be nice to reflect of a DB table (or EF entity) and populate the records based on the column types/names

**Comment by aliostad** [comment]
Thank you! We are happy to accept PR if you would like to add this functionality.

**Comment by patagoniahiker** [comment]
I would like to add, but where do I begin and how would I, some help to begin would be great
